/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio_estadistica2;
import java.text.NumberFormat;
import laboratorio_estadistica2.PruebaDeHipotesis;
/**
 *
 * @author dsm
 */
public class Coladerer extends javax.swing.JFrame {

    NumberFormat nf = NumberFormat.getNumberInstance();
    PruebaDeHipotesis prueba;
    
    /**
     * Creates new form Coladerer
     */
    public Coladerer(PruebaDeHipotesis prueba) {
        initComponents();
        this.prueba = prueba;
        zaLabel.setText(nf.format(prueba.zr));
        zrLabel.setText(nf.format(prueba.zt));
        if(prueba.acepta)
        {
            conclusionLabel.setText("SE CONCLUYE QUE LA HIPOTESIS SE ACEPTA");
        }else
        {
            conclusionLabel.setText("SE CONCLUYE QUE LA HIPOTESIS NO SE ACEPTA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        zaLabel = new javax.swing.JLabel();
        zrLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        conclusionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/cola a la derechaBIG.png"))); // NOI18N

        zaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zaLabel.setForeground(new java.awt.Color(246, 96, 7));

        zrLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zrLabel.setForeground(new java.awt.Color(255, 0, 37));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Zr =");

        conclusionLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zaLabel)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(zrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conclusionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jLabel3)
                    .addContainerGap(660, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zaLabel)
                .addGap(99, 99, 99)
                .addComponent(zrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conclusionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(449, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(370, 370, 370)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conclusionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel zaLabel;
    private javax.swing.JLabel zrLabel;
    // End of variables declaration//GEN-END:variables
}
