

package laboratorio_estadistica2;

import java.text.NumberFormat;
import laboratorio_estadistica2.PruebaDeHipotesis;



public class DosColas extends javax.swing.JFrame {

    NumberFormat nf = NumberFormat.getNumberInstance();
    PruebaDeHipotesis prueba;
    /**
     * Creates new form DosColas
     */
    public DosColas(PruebaDeHipotesis prueba) {
        initComponents();
        this.prueba = prueba;
        zaLabel.setText(nf.format(prueba.zr));
        minusZaLabel.setText("-"+nf.format(prueba.zr));
        if(prueba.zt < 0)
        {
            double temp = prueba.zt * -1;
            zrLabel.setText("-"+nf.format(temp));
        }else
        {
           zrLabel.setText(nf.format(prueba.zt)); 
        }
        
        System.out.println(prueba.zt);
        if(prueba.acepta)
        {
            conclusionLabel.setText("SE CONCLUYE QUE LA HIPOTESIS SE ACEPTA");
        }else
        {
            conclusionLabel.setText("SE CONCLUYE QUE LA HIPOTESIS NO SE ACEPTA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        zaLabel = new javax.swing.JLabel();
        minusZaLabel = new javax.swing.JLabel();
        zrLabel = new javax.swing.JLabel();
        Labell1 = new javax.swing.JLabel();
        conclusionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/dos colasBIG.png"))); // NOI18N

        zaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zaLabel.setForeground(new java.awt.Color(253, 84, 2));
        zaLabel.setText("jLabel2");

        minusZaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        minusZaLabel.setForeground(new java.awt.Color(253, 84, 2));
        minusZaLabel.setText("jLabel2");

        zrLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zrLabel.setForeground(new java.awt.Color(253, 2, 28));
        zrLabel.setText("Zr =");

        Labell1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Labell1.setForeground(new java.awt.Color(253, 84, 2));
        Labell1.setText("Zr =");

        conclusionLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        conclusionLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minusZaLabel)
                .addGap(187, 187, 187)
                .addComponent(zaLabel)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Labell1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conclusionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zaLabel)
                    .addComponent(minusZaLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labell1))
                .addGap(18, 18, 18)
                .addComponent(conclusionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labell1;
    private javax.swing.JLabel conclusionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minusZaLabel;
    private javax.swing.JLabel zaLabel;
    private javax.swing.JLabel zrLabel;
    // End of variables declaration//GEN-END:variables
}
